export const GET_ALL_CUSTOMER_REQUEST = "GET_ALL_CUSTOMER_REQUEST";
export const GET_ALL_CUSTOMER_SUCCESS = "GET_ALL_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER_FAILURE = "GET_ALL_CUSTOMER_FAILURE";

export const CREATE_CUSTOMER_REQUEST = "CREATE_CUSTOMER_REQUEST";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_FAILURE = "CREATE_CUSTOMER_FAILURE";

export const UPDATE_CUSTOMER_REQUEST = "UPDATE_CUSTOMER_REQUEST";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE";

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";

export const GET_CUSTOMER_BY_ID_REQUEST = "GET_CUSTOMER_BY_ID_REQUEST";
export const GET_CUSTOMER_BY_ID_SUCCESS = "GET_CUSTOMER_BY_ID_SUCCESS";
export const GET_CUSTOMER_BY_ID_FAILURE = "GET_CUSTOMER_BY_ID_FAILURE";

export const GET_CUSTOMER_NAME_REQUEST = "GET_CUSTOMER_NAME_REQUEST";
export const GET_CUSTOMER_NAME_SUCCESS = "GET_CUSTOMER_NAME_SUCCESS";
export const GET_CUSTOMER_NAME_FAILURE = "GET_CUSTOMER_NAME_FAILURE";

export const GET_CUSTOMER_PHONE_REQUEST = "GET_CUSTOMER_PHONE_REQUEST";
export const GET_CUSTOMER_PHONE_SUCCESS = "GET_CUSTOMER_PHONE_SUCCESS";
export const GET_CUSTOMER_PHONE_FAILURE = "GET_CUSTOMER_PHONE_FAILURE";
