export const GET_ALL_TICKET_REQUEST = "GET_ALL_TICKET_REQUEST";
export const GET_ALL_TICKET_SUCCESS = "GET_ALL_TICKET_SUCCESS";
export const GET_ALL_TICKET_FAILURE = "GET_ALL_TICKET_FAILURE";

export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAILURE = "CREATE_TICKET_FAILURE";

export const UPDATE_TICKET_REQUEST = "UPDATE_TICKET_REQUEST";
export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_FAILURE = "UPDATE_TICKET_FAILURE";

export const DELETE_TICKET_REQUEST = "DELETE_TICKET_REQUEST";
export const DELETE_TICKET_FAILURE = "DELETE_TICKET_FAILURE";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";

export const CHECKIN_TICKET_REQUEST = "CHECKIN_TICKET_REQUEST";
export const CHECKIN_TICKET_SUCCESS = "CHECKIN_TICKET_SUCCESS";
export const CHECKIN_TICKET_FAILURE = "CHECKIN_TICKET_FAILURE";
