export const GET_ALL_BILL_REQUEST = "GET_ALL_BILL_REQUEST";
export const GET_ALL_BILL_SUCCESS = "GET_ALL_BILL_SUCCESS";
export const GET_ALL_BILL_FAILURE = "GET_ALL_BILL_FAILURE";

export const CREATE_BILL_REQUEST = "CREATE_BILL_REQUEST";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAILURE = "CREATE_BILL_FAILURE";

export const UPDATE_BILL_REQUEST = "UPDATE_BILL_REQUEST";
export const UPDATE_BILL_SUCCESS = "UPDATE_BILL_SUCCESS";
export const UPDATE_BILL_FAILURE = "UPDATE_BILL_FAILURE";

export const DELETE_BILL_REQUEST = "DELETE_BILL_REQUEST";
export const DELETE_BILL_SUCCESS = "DELETE_BILL_SUCCESS";
export const DELETE_BILL_FAILURE = "DELETE_BILL_FAILURE";

export const GET_BILL_BY_ID_REQUEST = "GET_BILL_BY_ID_REQUEST";
export const GET_BILL_BY_ID_SUCCESS = "GET_BILL_BY_ID_SUCCESS";
export const GET_BILL_BY_ID_FAILURE = "GET_BILL_BY_ID_FAILURE";

export const GET_BILL_BY_PLATENUMBER_REQUEST =
  "GET_BILL_BY_PLATENUMBER_REQUEST";
export const GET_BILL_BY_PLATENUMBER_SUCCESS =
  "GET_BILL_BY_PLATENUMBER_SUCCESS";
export const GET_BILL_BY_PLATENUMBER_FAILURE =
  "GET_BILL_BY_PLATENUMBER_FAILURE";
